# Generated by Django 2.0.6 on 2018-06-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='artists',
            field=models.TextField(blank=True, max_length=25500, verbose_name='Artists'),
        ),
    ]
