# Generated by Django 2.0.6 on 2018-06-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_range',
            field=models.CharField(blank=True, max_length=48, verbose_name='Date Range'),
        ),
    ]
