# Generated by Django 2.0.6 on 2018-06-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='artists',
            field=models.TextField(blank=True, max_length=25500, verbose_name='Artists (Separate multiple artists by comma)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cities',
            field=models.CharField(default='San Francisco', max_length=255, verbose_name='Cities (Separeate multiple  cities by comma)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_range',
            field=models.CharField(blank=True, max_length=48, verbose_name='Date Range (YYY-MM-DD,YYY-MM-DD)'),
        ),
    ]
