# Generated by Django 2.0.6 on 2018-06-30 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of Group')),
                ('cities', models.CharField(default='San Francisco', max_length=255, verbose_name='Cities')),
                ('artists', models.TextField(blank=True, max_length=25500, verbose_name='Artists')),
                ('date_range', models.CharField(blank=True, max_length=48, verbose_name='Date Range')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Your Real Name'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
